branch-defaults:
  deployment:
    environment: TAEN-dev
  master:
    environment: TAEN-dev
    group_suffix: null
global:
  application_name: TAEN
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: git
packages:
  yum:
    git: []
    postgresql93: []
    postgresql93-devel: []
