# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 04:18
from __future__ import unicode_literals

import TAEN_APP.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertaener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anonymous', max_length=32)),
                ('pitch', models.CharField(blank=True, max_length=5000, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=TAEN_APP.models.imgUploadLocation)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.IntegerField(choices=[(0, 'Recording'), (1, 'Musician'), (2, 'Producer')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entertaener',
            name='talent',
            field=models.ManyToManyField(to='TAEN_APP.Talent'),
        ),
        migrations.AddField(
            model_name='entertaener',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
