# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAEN_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, choices=[('F', 'Film'), ('P', 'Photography'), ('M', 'Music')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='entertaener',
            name='email',
        ),
        migrations.RemoveField(
            model_name='entertaener',
            name='userAuthentication',
        ),
        migrations.AddField(
            model_name='entertaener',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='entertaener',
            name='pitch',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='entertaener',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='entertaener',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAEN_APP.Industry'),
        ),
    ]
