# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAEN_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('entertaener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolioLink', to='TAEN_APP.Entertaener')),
            ],
        ),
    ]
