# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TAEN_APP', '0002_auto_20160520_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertaener',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
