# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAEN_APP', '0003_auto_20160610_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertaener',
            name='equipment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entertaener',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
