# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAEN_APP', '0003_entertaener_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertaener',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='entertaener',
            name='user',
        ),
        migrations.DeleteModel(
            name='Entertaener',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
