# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAEN_APP', '0004_auto_20160614_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='talent',
            field=models.IntegerField(choices=[(1, 'Artist'), (2, 'Producer'), (0, 'Recording Engineer'), (3, 'Sound Mixer')], default=1),
            preserve_default=False,
        ),
    ]
