# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 01:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TAEN_APP', '0004_auto_20160521_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertaener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anonymous', max_length=32)),
                ('pitch', models.CharField(blank=True, max_length=5000)),
                ('portfolio', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, choices=[('F', 'Film'), ('P', 'Photography'), ('M', 'Music')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='entertaener',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAEN_APP.Industry'),
        ),
        migrations.AddField(
            model_name='entertaener',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
